DROP TABLE IF EXISTS Ratelimits;
DROP TABLE IF EXISTS Keys;
DROP TABLE IF EXISTS Permissions;
DROP TABLE IF EXISTS Resources;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS KeyRoleIntersect;
DROP TABLE IF EXISTS RolePermIntersect;

DROP INDEX IF EXISTS RolesByID;
DROP INDEX IF EXISTS RolesByPrecedence;
DROP INDEX IF EXISTS PermissionsPerResource;
DROP INDEX IF EXISTS RolesPerKey;
DROP INDEX IF EXISTS PermissionsPerRole;
DROP INDEX IF EXISTS KeysPerPermission;
DROP INDEX IF EXISTS RolesByRoleType;